### ISSUE TITLE
Any idea what was broken in my quantizing code?

### ISSUE THREAD

**Issue by jeremywen** [jhoar/AmalgamatedHarmonics#1]
I would like to fix it so your readme doesn't have to say mine is broken.  I will be looking into it also.

**Comment by jhoar** [comment]
I found that when I added the octave (12) to the list of notes in the arrays it worked. (it seemed to jump up to next octave and skip the last note in the scale). Also, I updated the README. I am mildly surprised that anyone has even noticed this poor attempted at module...

**Comment by jhoar** [comment]
Well, it looks like it's fixed, so closing it here.
