### ISSUE TITLE
Progress Module Crash

### ISSUE THREAD

**Issue by blackearth2014** [jhoar/AmalgamatedHarmonics#10]
Your Progress module keeps crashing vcvrack on my Windows10.

**Comment by jhoar** [comment]
Thanks I'll have a look at what's happening.

**Comment by blackearth2014** [comment]
It was on load but somehow it is working now on my Windows PC.

**Comment by blackearth2014** [comment]
Here is a screen shot.

![progress](https://user-images.githubusercontent.com/7956901/34492816-48fe7e90-efb7-11e7-8bb2-9bebac0ea42f.jpg)

**Comment by jhoar** [comment]
I have not managed to make it crash, despite my best efforts. I will close this now and keep an eye on this in the future.

**Comment by blackearth2014** [comment]
Your last release update to your modules actually fixed the issue. Thanks
