### ISSUE TITLE
Progress doesn't seem to remember trigger mode when you load a patch

### ISSUE THREAD

**Issue by Chaircrusher** [jhoar/AmalgamatedHarmonics#11]

**Comment by Chaircrusher** [comment]
Subject line says it all. When you exit Rack, and re-run, Progress doesn't remember the trigger mode set in the context menu.

**Comment by jhoar** [comment]
Thanks for you feedback!

Completely correct, I did not get round to implementing the serialisation part.

I've fixed this and I'll push it out in the next version (due soon...)

**Comment by jhoar** [comment]
Closed with b96a909f50d965545628ac7ffa7341b3355ddde9
