### ISSUE TITLE
v/oct to key - is it possible?

### ISSUE THREAD

**Issue by dev-dsp** [jhoar/AmalgamatedHarmonics#12]
Hi, is it possible to somehow convert v/oct CV to what is called 'root' or 'key'?
So that I could use it like that:
![image](https://user-images.githubusercontent.com/4235552/35597707-df906906-0630-11e8-8746-00c78ac7af70.png)

**Comment by jhoar** [comment]
It should be possible with a small code change. What platform are you using? I'll see if I can cook something up for you.

**Comment by dev-dsp** [comment]
it is archlinux. thanks a lot!

**Comment by jhoar** [comment]
Hi,

Try this:

[AmalgamatedHarmonics-0.5.8-p1-lin.zip](https://github.com/jhoar/AmalgamatedHarmonics/files/1684877/AmalgamatedHarmonics-0.5.8-p1-lin.zip)

You'll need to open the context menu and select 'Chromatic (V/OCT)' at the bottom. The ROTL and ROTR inputs will still shift the current key around the circle, but the ROOT input should track across the keyboard (standard V/OCT) inputs

**Comment by dev-dsp** [comment]
It has weird bug - I can get ROOT as G|Em only when I send C# to this input; when I send G - I get Db|Bbm.

However, it works and it is awesome! Just what I wanted.

**Comment by jhoar** [comment]
That's odd. Which is the keyboard module you have? It looks very useful. 

I think it might just be a question of the lights being bugged, but I'd like to fix it and put it into the next main release.

**Comment by dev-dsp** [comment]
It is from Autodafe plugin, module named simply 'Keyboard'

**Comment by dev-dsp** [comment]
![out-2018-02-02_14 09 53](https://user-images.githubusercontent.com/4235552/35730585-b12839a0-0823-11e8-88ab-cc131c6160a5.gif)

**Comment by jhoar** [comment]
Hmm, it's pretty broken.

**Comment by jhoar** [comment]
OK, so I think it's working now...

[AmalgamatedHarmonics-0.5.8-p2-lin.zip](https://github.com/jhoar/AmalgamatedHarmonics/files/1692086/AmalgamatedHarmonics-0.5.8-p2-lin.zip)

**Comment by dev-dsp** [comment]
Just tested it - version p2 works correctly.

**Comment by jhoar** [comment]
Great - thanks for the feedback! Fixed in 8ef074e1e64ed04c038b54fff20297cc315b5987
