### ISSUE TITLE
Scale Quantizer needs a Latch/Momentary switch

### ISSUE THREAD

**Issue by Obewankobe** [jhoar/AmalgamatedHarmonics#14]
I thought the Scale Quantizer would be the perfect interface module to trigger drum sounds with my Maschine pads. However though it does take in the Iv/Oct pitch from the MIDI interface and sound the correct drum module based on that pitch, it then is in latched mode at 10V until another pad is hit.  Then that pad is in latched mode until another one is hit.  

This makes it impossible to actually play a drum sequence in.  Such as Hi Hats repetitively every 16th for instance.  I'm routing the Audio outs back to Reaper for recording so that is why I'm attempting to do it manually instead of self generating something random.

I've not figured out a way to reset the output to 0V automatically after the pad is hit as there is no reset input that I can find.  Maybe a switch for Latched/Momentary mode could be added.

Or if you know of a way to do the reset with some additional module please let me know.

Thanks, these are some really useful modules!

ObeWanKobe

**Comment by jhoar** [comment]
Hi! Thanks for the feedback.

Maybe Michael Hetrick's Delta module could be part of what you are looking for, it will generate a trigger when a voltage changes. Used with the sample and hold function from the Audible Instruments Utilities module it might be what you need.

https://github.com/mhetrick/hetrickcv

I've just added sample and hold for the next version of Scale Quantizer due with 0.6 of Rack, so it should not be too difficult to add a momentary mode which will stay at the quantized pitch for, say, 1 ms and then reset to 0V. It would fire on a quantised pitch change (and maybe spit out a gate as well)

**Comment by Obewankobe** [comment]
Thanks for the quick response.  I will check out the suggestions you made.  Also, the changes you mention would make the Scale quantizer nearly perfect for any type of application.  Looking forward to seeing those.

You might also want to think about adding a hard reset CV input to the module as well. Could be useful in some cases.

**Comment by jhoar** [comment]
In the end I am not going to fix this within the module; a reset to 0V does not make sense since a quantizer resetting to middle-C is almost never the desired behaviour. I do think it should be possible with some other modules in the patch.
