### ISSUE TITLE
Attenuator on SLN

### ISSUE THREAD

**Issue by benirose** [jhoar/AmalgamatedHarmonics#18]
I am a huge fan of the SLN and use it pretty frequently. I often find myself using an attenuator to clamp down the output quite a bit. I was wondering what you thought of adding an attenuation knob to the module to reduce need of having to add a secondary module. Having this full functionality in 3HP would be killer.

I haven't done any VCV Rack dev yet, but I've looked through a lot of module source code and I think this is something I could probably do if you're interested in a PR.

**Comment by jhoar** [comment]
Fixed in 0.6.4.
