### ISSUE TITLE
AmalgamatedHarmonics v1 crashes in VCV Rack v1 (regression b/c it worked in "#54896ea"

### ISSUE THREAD

**Issue by NielsMayer** [jhoar/AmalgamatedHarmonics#23]
Running "VCV Rack v1.dev.d648860" On Kubuntu 18.04.2LTS, and using current v1 of AmalgamatedHarmonics, I get a crash instantly when I try to add any of the AH plugin modules to my rack. 

Note that this seems to be a recent regression as I was able to use AH plugins in version "#54896ea" 

See also https://github.com/VCVRack/Rack/issues/89#issuecomment-488412456 and subsequent comments.

Enclosed is output from gdb run .
[AmalgamatedHarmonics.gdb.txt](https://github.com/jhoar/AmalgamatedHarmonics/files/3139397/AmalgamatedHarmonics.gdb.txt)

**Comment by NielsMayer** [comment]
Note the crash occurred on adding "Polyscope" which worked previously

> #5  0x00007fffec4af002 in PolyScope::PolyScope() (this=0x555556aa40c0) at src/PolyScope.cpp:57

**Comment by jhoar** [comment]
Hi Niels,

Thanks for the report. It should be fixed in a96ab9a7eb567cae4acd6a501e6b8fb6176fe5d8
