### ISSUE TITLE
Rack v1: Compile error on Mac platform

### ISSUE THREAD

**Issue by cschol** [jhoar/AmalgamatedHarmonics#25]
When cross-compiling the Mac version of the `v1` plugin (clang 6.0.0), I get the following compile error:

```
src/PolyScope.cpp:11:26: error: implicit instantiation of undefined template 'std::__1::array<NVGcolor, 16>'
std::array<NVGcolor, 16> colourMap = {
                         ^
/home/cschol/src/osxcross/target/bin/../SDK/MacOSX10.13.sdk/usr/include/c++/v1/__tuple:223:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
2 warnings and 1 error generated.
/home/cschol/src/Rack-1.0/compile.mk:61: recipe for target 'build/src/PolyScope.cpp.o' failed
```

Windows (cross-compile) and GNU/Linux (Ubuntu 18.04) build successfully.

**Comment by jhoar** [comment]
I do not have a Mac any more :( so I can't debug this directly. Unless you see something obviously wrong that I am doing I think the easiest solution is to switch back to boring old arrays.

**Comment by cschol** [comment]
No. Let me take a look and get back to you.

**Comment by cschol** [comment]
Looks like `Polyscope.cpp` just need an `#include <array>` at the top.

**Comment by jhoar** [comment]
new commit:

e001cd013eccc9bdf48c8572cf565f85d2e2749a

**Comment by cschol** [comment]
Works. Thanks.
