### ISSUE TITLE
PolyScope v1.0.1 number of channels.

### ISSUE THREAD

**Issue by therealkitman** [jhoar/AmalgamatedHarmonics#29]
Hi, just doodling with the V1 Rack and your modules. I sent a 5 voice poly chord to PolyScope but it only seems to display the first 2 voices. PolyProbe seems to be ok. See pic below.
Regards,
Chris.

![image](https://user-images.githubusercontent.com/14888092/59957362-31b8a580-94ca-11e9-874a-c204fc5aa483.png)

EDIT: I think maybe ignore this. Just counted the straight lines (11) which means the other 5 must be active. Maybe the colour separation for each line could better contrasted?

**Comment by jhoar** [comment]
Hi! Thanks for your feedback. 

I've added a number of selectable colour schemes available from a context menu which should keep most people happy. The top left one is the new default.

![Capture](https://user-images.githubusercontent.com/13257489/59961825-7b5ebb80-94dd-11e9-9d57-8b5042be8fd5.JPG)

**Comment by therealkitman** [comment]
Sounds good. Can the user define their own colour scheme as these seem a little too similar?
PS. If you added a trigger feature this would make a nice little scope ;)

**Comment by jhoar** [comment]
User defined colour maps now in v1.0.2. Leaving this open for now in case I come back to implement trigger input

**Comment by therealkitman** [comment]
All this and Rainbow+Spectrum too :+1: 
Thank you, looks good for me now!!

**Comment by therealkitman** [comment]
Hi again. Just a enhancement request if you do come back with a trigger :wink: 
It's good that the unplugged channels no longer display. But it's annoying that the channels in use cannot make use of the full display real estate - see the 6 channels from Rainbow can only occupy the bottom portion of the display. It would be nice if there could be either an OFFSET knob to adjust the location of the traces or some clever algorithm that would auto scale the display for maximum use based on the number of connected channels.
Thanks.

![image](https://user-images.githubusercontent.com/14888092/64750300-139f9600-d54b-11e9-99af-36d2a819e082.png)

**Comment by jhoar** [comment]
So... what trigger functionality are you missing? To set the trigger level?

**Comment by therealkitman** [comment]
I like to trigger a one-off capture and hold so I can compare traces. Polyscope is free running. Most other scopes with triggers don't hold - I think Submarine's scope is the exception but limited to 2 traces. 

But I see now Submarine's Logic Analyzer can now display analogue signals too. So from my perspective there is that tool already for me as I like to explore and understand how things work and are related (I used to use a digital storage oscilloscope years ago when I was a tech).

In regard to Polyscope what does the triggering - channel 1 rise? Or perhaps a new trigger input socket? Maybe this is hijacking your module's original intent? 

But I still think maximizing the display real estate when using fewer channels (and maybe having a Ctrl+drag option to widen the screen) is a good idea.
Thanks.
