### ISSUE TITLE
Linux Release

### ISSUE THREAD

**Issue by t0m5k1** [jhoar/AmalgamatedHarmonics#3]
Please can we have a Linux release?

**Comment by phdsg** [comment]
[AmalgamatedHarmonics-devda6319b-lin.zip](https://github.com/jhoar/AmalgamatedHarmonics/files/1503873/AmalgamatedHarmonics-devda6319b-lin.zip)

**Comment by t0m5k1** [comment]
Thank you so much :)

**Comment by jhoar** [comment]
Thanks phdsg! I soon as stop for second and get a linux vm sorted out, I'll make linux releases with the rest.

**Comment by jhoar** [comment]
I have built a Linux version of the new release, but can't test it in within a VM. Please let me if there are any problems.
