### ISSUE TITLE
Feature Request: PolyProbe showing note values

### ISSUE THREAD

**Issue by neonpixii** [jhoar/AmalgamatedHarmonics#31]
This is a feature request. It would be very useful for the PolyProbe module to display the note a given channel is currently playing, alongside the voltage. A display like "C♯3+23" for a voltage 23 cents sharp of C♯3, or "E♭2-31" for a voltage 31 cents flat of E♭2, would work plenty fine

It would make a wonderful utility even more useful by being kinda like a polyphonic version of the Skrylar "What Note" module.

**Comment by jhoar** [comment]
That's an interesting idea. I'll put it in the next release (should be soon)

**Comment by neonpixii** [comment]
Thank you!

**Comment by jhoar** [comment]
Done in v1.0.2.

Right click -> Algorithm -> Note(A+B). You can leave the B input empty.
