### ISSUE TITLE
arp 3.1 appears to play too many notes

### ISSUE THREAD

**Issue by dag2099** [jhoar/AmalgamatedHarmonics#34]
Windows 7 64
VCVrack 1.1.4

I've been using Arp 3.1 for a while but I've just noticed that it appears to play an extra note.
Using Merge to put together an 8 part polyphonic signal and then play a melody yields 9 notes instead of 8 when in either "left" or "right" mode. The extra note appears to be have a value of 0.000. Going back over some of my other patches (some of which i've even made videos of) they seem to exhibit the same behavior.
Thx.

**Comment by AmalgamatedHarmonics** [comment]
HI,

Thanks for feedback. Let me have a look at it and see what's up.

cheers,

john

**Comment by jhoar** [comment]
I can't reproduce it, with a simple patch (attached) it seems to be ok. Can you give me a patch to test with?

[Arp31test.zip](https://github.com/jhoar/AmalgamatedHarmonics/files/3585783/Arp31test.zip)

john

**Comment by dag2099** [comment]
I tried your test patch and it counted 9 numbers one of which was 0.000. for whatever reason it displayed the 0.000 as yellow. Let me just try and redownload your module...
...no it still counts 9 steps rather than 8.

**Comment by jhoar** [comment]
I am baffled. I'm not sure what else to suggest.

![Capture](https://user-images.githubusercontent.com/13257489/64607707-56d1fb80-d3c9-11e9-8dfa-3ba00414f678.JPG)

**Comment by AmalgamatedHarmonics** [comment]
Sorry, wrong image!

**Comment by paulpiko** [comment]
This might show the same problem. It plays C4 A4 B4, even though there are only 2 notes, A4 and B4,  in the poly cable.

![image](https://user-images.githubusercontent.com/56526215/66726880-7c9a6680-ee87-11e9-8794-ff19ca6adac4.png)

**Comment by zyx** [comment]
I've been seeing this issue under Linux - Debugging with GDB shows that Arp3.1 is actually calling  `RightArp::isArpeggioFinished()` from `ArpeggiatorMkII.cpp`. This copy of `RightArp::isArpeggioFinished()` seems to have an off-by-one bug that causes an extra note to be played.

Removing ArpeggiatorMkII from the plugin fixes the issue, but just renaming `Arpeggio` and subclasses in ArpeggiatorMkII should also do the trick.

As to the root cause, I'll hazard a guess and say that this may be a linking issue - perhaps there's some link time optimization going on?

**Comment by jhoar** [comment]
Hi!

Great! Thanks for tracking that down - I was not getting anywhere with that. 

john

**Comment by zyx** [comment]
Hi John, I tried your change but just get a segfault when adding the Arp3.1 module from the browser. Renaming the arpeggiator subclasses (LeftArp -> LeftArp2 etc)  in addition to the parent class fixes the issue though.

**Comment by AmalgamatedHarmonics** [comment]
Great, that's what I have done in fact. Am testing it now with some new
stuff. Hope to have it ready next week

John

**Comment by jhoar** [comment]
Fixed for next release.

**Comment by jhoar** [comment]
Closed in 1.0.4
