### ISSUE TITLE
Scale Quantizer (legacy/resurrected)V1.0.2 : Degrees Issue

### ISSUE THREAD

**Issue by therealkitman** [jhoar/AmalgamatedHarmonics#35]
Declaration: I am no expert in music theory.
Hi. Just doing some random noodling as saw something odd.
In the quantizer I set an A minor scale and wanted to check the gates of the Degree output. In an A minor scale I expected A to be degree 1, B degree 2, C degree 3 etc.
But I see that C is ♭3, F is ♭6 and G is ♭7. I would have expected degrees just 3, 6 and 7.
Have I botched up my understanding of simple minor scales or is the quantizer amiss?
Thanks.
PS. It be nice is the Key and Scale inputs has knob controls like it's bigger brother :wink: 
![image](https://user-images.githubusercontent.com/14888092/64752148-0f767700-d551-11e9-8d44-8ffdd5afa9f4.png)

Edit: Just read this at [basicmusictheory](https://www.basicmusictheory.com/a-minor-scale) - the degrees are putting out an A Major scale, not a minor.

**Comment by jhoar** [comment]
You are correct, if fact I was confused between degree and interval. The upper outputs should be labelled 'Interval' not 'Degree'. In the case of the natural Minor scale, the scale consists of minor (flat) third, sixth and seventh intervals. I have fixed the UI

**Comment by jhoar** [comment]
Closed in 1.0.4
