### ISSUE TITLE
Feature request: Pan up and down on the PolyScope

### ISSUE THREAD

**Issue by smerkley** [jhoar/AmalgamatedHarmonics#36]
When visualizing just a few poly channels, like 2 to 4, it can be hard to see them individually since the spread knob spreads from the center 8th channel even if you're only using a few poly channels. If you could pan up and down as well as scale/spread the waves it'd be a lot better for visualizing just a few poly channels.

**Comment by jhoar** [comment]
Already implemented, will be released in next version.
