### ISSUE TITLE
Feature Request for Progress II

### ISSUE THREAD

**Issue by ajbmorris** [jhoar/AmalgamatedHarmonics#40]
Lovely module! Would it be possible to be able to address individual steps via CV, so that within a part of 8 chords you could randomly cue any one of the eight rather then just run them as a linear clocked sequence?

**Comment by jhoar** [comment]
Nice idea. Implemented for next release

**Comment by jhoar** [comment]
Closed in 1.0.4

**Comment by ajbmorris** [comment]
Thanks and Merry Christmas!
