### ISSUE TITLE
port to Rack v2 ?

### ISSUE THREAD

**Issue by davephillips** [jhoar/AmalgamatedHarmonics#45]
Hi John ! 

Do you plan to port your modules to VCV Rack v2 ? I have Galaxy, Arp31, Arp32, and Progress2 working fine, but I have a font issue with the chord name display in Progress2. Hopefully I'll figure it out on my own, but feel free to suggest any possible fixes. :)

Thanks again for the excellent plugin !

Best regards,

dp

**Comment by jhoar** [comment]
I have made all the necessary changes so it will run; I'll have a look at the v2 improvements available.

**Comment by Torinbob** [comment]
Hi John,

Just to let you know that after compiling for v2 and trying in the Rack VST, I am riding that your Imp module crashes Rack when it restarts. All works fine adding from the browser and using it, but after I save and quit Bitwig, then reopen it, the Rack VST immediately crashes if Imp is in the patch (and it doesn't crash if I take Imp out).

In fact I don't completely need to quit and reopen Bitwig, I can just delete the Rack VST, then undo, and Rack will crash as it comes back on the undo if Imp is in the patch.

I'll see if I can do some more testing to see if this issue affects your other modules too.

thanks,
Steve

**Comment by falkTX** [comment]
I have been successfully using it as part of https://github.com/DISTRHO/Cardinal
The restriction of "cant load resources when widget is created" doesn't apply to Cardinal, only to Rack Pro, so there is no crash on project load (that use these modules).

There is a possible license issue though, I have opened a new ticket for that.

**Comment by Torinbob** [comment]
Hi John,

I meant to add earlier that this issue has affected a lot of plugins and is probably related to font reference storage across frames (in any module that uses custom fonts).

Please see this link on how to properly implement this:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by nesdnuma** [comment]
+1 for a Rack 2 version!

**Comment by jhoar** [comment]
@Torinbob thanks! I'm slowly working my way though the UI updates I wanted to do and fix the font references as well.

**Comment by ranchy** [comment]
Yes, please update if you can. I love the Imperfect module and I used it on many patches...

**Comment by jhoar** [comment]
Hi Lars,
There are no holdups really - there is an outstanding bug that crashes the module but I have not been able to reproduce it despite a lot of time wasted on this; I never got round to testing it properly in the VST environment.
To be honest had it has not been on my mind for a while. I should just push it to the library,

john

    On Wednesday, 9 March 2022, 16:04:42 CET, Lars Bjerregaard ***@***.***> wrote:  
 
 


Hi John

Any updates? It builds fine for v2 now and all the modules load. I can see you stopped work end of January. Are there any holdups before submitting it to the library? Anything we can help with?

Thanks!

All the best,
Lars

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rubyglow** [comment]
Yeah, you should just submit it to the library. Better to get it into the hands of people for v2. Then they can submit the odd bug-report and you can deal with it as time permits, or other people will help you which is quite likely.

Thanks, looking forward to it!

**Comment by jhoar** [comment]
v2 released

**Comment by ranchy** [comment]
Thank You!
