### ISSUE TITLE
[Progress mk III] zero-based indexing is confusing UX

### ISSUE THREAD

**Issue by brylie** [jhoar/AmalgamatedHarmonics#46]
The use of zero-based indexing for the chord sequence is confusing when the steps are 1-based:

![image](https://user-images.githubusercontent.com/17307/139801658-59028f23-0d6c-426b-915c-9614d242b530.png)

It would be more consistent and intuitive if the chord sequence used 1-based indexing, since people are already familiar with counting things starting at one rather than zero.

The zero-based indexing may have leaked into the UI from the underlying implementation but is a language design decision rather than a UX feature :-)

**Comment by jhoar** [comment]
Thanks! - updated in 3076935
