### ISSUE TITLE
How to sync progress with internal clock source (Impromptu Clkd)

### ISSUE THREAD

**Issue by brylie** [jhoar/AmalgamatedHarmonics#47]
I use the Impromptu clock modules as master clocks for my patches. However, when I connect the [Clkd](https://library.vcvrack.com/ImpromptuModular/Clocked-Clkd) `clk` signal to the clock input for Progress, the plugin jumps forward and slows down rather than adopting the bpm from Clkd.

How can I use Clkd as an external clock source for Amalgamated Harmonics modules (where applicable)?

**Comment by jhoar** [comment]
Plug it into EXT

**Comment by brylie** [comment]
Perhaps the label could read "EXT CLK" similar to VCV SEQ-3 to make its purpose more clear?
