### ISSUE TITLE
Clarifications on EurostileBold.ttf usage

### ISSUE THREAD

**Issue by falkTX** [jhoar/AmalgamatedHarmonics#48]
Hi there.
Opening an issue asking for clarification of EurostileBold.ttf origins, is this from Windows?

Because I do not think using it as-is like you do is allowed.
Per https://docs.microsoft.com/en-us/typography/font-list/eurostile and (linked in that page) https://www.fonts.com/content/microsoft-typography one needs a license grant before being able to use such font.

Would be great if you could provide clear license details for the artwork files you import.
Thanks.

**Comment by jhoar** [comment]
Hi. I do not even remember where I got it from. I don't think it was from Windows though. 

I am in the middle of reskin for V2 and was going to change everything to Roboto. So I might as well clean things up for V1

**Comment by falkTX** [comment]
That would be much appreciated, please consider adding a note around the roboto font too if you can.

**Comment by falkTX** [comment]
I see the font is gone now, that solves it I guess :sweat_smile: 
thanks!
