### ISSUE TITLE
Clicking Polyscope in Module browser exits VCV Rack v2.0

### ISSUE THREAD

**Issue by Petervos2018** [jhoar/AmalgamatedHarmonics#50]
On windows 10 VCV (stand-alone) closes when selecting Polyscope in the Module browser (try it a few times).
EDIT left-click and hold works best to force the error.

Greetings Peter.

[7.962 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
32:  0x0
31:  0x0
30: _C_specific_handler 0x7ffe95827f60
29: _chkstk 0x7ffe95df1fb0
28: RtlRaiseException 0x7ffe95da1020
27: KiUserExceptionDispatcher 0x7ffe95df0bd0
26: ZN16PolyScopeDisplay4drawERKN4rack6widget6Widget8DrawArgsE 0x7ffe5a1d8940
25: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
24: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
23: ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE 0x7ffe474237e0
22: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
21: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
20: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
19: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
18: ZN4rack3app10RackWidget4drawERKNS_6widget6Widget8DrawArgsE 0x7ffe47436410
17: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
16: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
15: ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE 0x7ffe47460850
14: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
13: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
12: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
11: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
10: ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE 0x7ffe47458810
9: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
8: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
7: ZN4rack6window6Window4stepEv 0x7ffe47462970
6: ZN4rack6window6Window3runEv 0x7ffe474632a0
5: ZN4rack6window6Window3runEv 0x7ffe474632a0
4: ZN4rack6window6Window3runEv 0x7ffe474632a0
3: ZN4rack6window6Window3runEv 0x7ffe474632a0
2: ZN4rack6window6Window3runEv 0x7ffe474632a0
1: BaseThreadInitThunk 0x7ffe940f7020
0: RtlUserThreadStart 0x7ffe95da2630

[7.967 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 22. Stack trace:
49:  0x0
48: raise 0x7ffe9582abe0
47: abort 0x7ffe9582f1e0
46: ZN9__gnu_cxx27__verbose_terminate_handlerEv 0x7ffe5a79f4c0
45: ZN10__cxxabiv111__terminateEPFvvE 0x7ffe5a795cd0
44: ZSt9terminatev 0x7ffe5a8878d0
43: stbi_write_png 0x7ffe473f0600
42: gai_strerrorW 0x7ffe47885810
41: gai_strerrorW 0x7ffe47885810
40: gai_strerrorW 0x7ffe47885810
39: RtlActivateActivationContextUnsafeFast 0x7ffe95d69900
38: LdrShutdownProcess 0x7ffe95dada50
37: RtlExitUserProcess 0x7ffe95dad980
36: FatalExit 0x7ffe940fe0a0
35: exit 0x7ffe9583a0d0
34: initterm_e 0x7ffe9583a580
33: raise 0x7ffe9582abe0
32: raise 0x7ffe9582abe0
31: raise 0x7ffe9582abe0
30: _C_specific_handler 0x7ffe95827f60
29: _chkstk 0x7ffe95df1fb0
28: RtlRaiseException 0x7ffe95da1020
27: KiUserExceptionDispatcher 0x7ffe95df0bd0
26: ZN16PolyScopeDisplay4drawERKN4rack6widget6Widget8DrawArgsE 0x7ffe5a1d8940
25: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
24: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
23: ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE 0x7ffe474237e0
22: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
21: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
20: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
19: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
18: ZN4rack3app10RackWidget4drawERKNS_6widget6Widget8DrawArgsE 0x7ffe47436410
17: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
16: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
15: ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE 0x7ffe47460850
14: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
13: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
12: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
11: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
10: ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE 0x7ffe47458810
9: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x7ffe474603e0
8: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x7ffe47460560
7: ZN4rack6window6Window4stepEv 0x7ffe47462970
6: ZN4rack6window6Window3runEv 0x7ffe474632a0
5: ZN4rack6window6Window3runEv 0x7ffe474632a0
4: ZN4rack6window6Window3runEv 0x7ffe474632a0
3: ZN4rack6window6Window3runEv 0x7ffe474632a0
2: ZN4rack6window6Window3runEv 0x7ffe474632a0
1: BaseThreadInitThunk 0x7ffe940f7020
0: RtlUserThreadStart 0x7ffe95da2630

**Comment by jhoar** [comment]
HI Peter,

Thanks for the report - and how to reproduce!

**Comment by jhoar** [comment]
Closed on 2.0.1
