### ISSUE TITLE
feature request and issue on EOS and EOC

### ISSUE THREAD

**Issue by soulbridge** [jhoar/AmalgamatedHarmonics#8]
a button to trigger the cycle would be useful to start a loop with EOS out
by the way,  EOS and EOC start before of the last note of the sequence

**Comment by jhoar** [comment]
Thanks for the feedback - yes, that's a interesting idea.

**Comment by jhoar** [comment]
FIRE button implemented which one-shots the sequence. EOC and EOS fire on the same (Rack internal) step as the last note in the cycle/sequence
Fixed in 6404302c5b0a71384d57881c579671b0df87e8de
