### ISSUE TITLE
build fail with simple error

### ISSUE THREAD

**Issue by davephillips** [jhoar/AmalgamatedHarmonics#9]
Linux Fedora 23
Rack 0.5.0

As I said, a simple error/fix.

g++  -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/Arpeggiator.cpp.o src/Arpeggiator.cpp
src/Arpeggiator.cpp: In member function ‘virtual void Arpeggiator::step()’:
src/Arpeggiator.cpp:168:20: error: expected ‘]’ before ‘)’ token
   if (pitchStatus[p) { //Plugged in 
                    ^
../../compile.mk:53: recipe for target 'build/src/Arpeggiator.cpp.o' failed
make: *** [build/src/Arpeggiator.cpp.o] Error 1

**Comment by jhoar** [comment]
Ugh, so clumsy. build before commit... build before commit...

FIxed in d7257f4b3b65d711459f1d48a7a596f975777801
